baseURL = "https://avi48437.github.io/"
publishDir = "docs"
languageCode = "en-us"
title = "Avi | Personal Website"
theme = "PaperMod"

[params]
customCSS = ["css/custom.css"]
math = true

  [params.label]
    icon = "/images/profile.jpg"
    text = "Avinandan Roy"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Avi48437"

[[params.socialIcons]]
  name = "email"
  url = "mailto:avi48437@example.com"

[params.homeInfoParams]
  Title = "Welcome ðŸ‘‹"
  Content = "This is my personal website where I document my learning and projects."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    name = "Bio"
    pageRef = "/bio/"
    weight = 1

  [[menu.main]]
    name = "Notes"
    pageRef = "/notes/"
    weight = 2

  [[menu.main]]
    name = "Blogs"
    pageRef = "/blogs/"
    weight = 3

  [[menu.main]]
    name = "Links"
    pageRef = "/links/"
    weight = 4

  [[menu.main]]
    name = "Travel"
    pageRef = "/travel/"
    weight = 5

  [[menu.main]]
    name = "Contact"
    pageRef = "/contact/"
    weight = 6
    
  [[menu.main]]
    name = "Paper Summary"
    url = "/papers/"
    weight = 7