baseURL = "https://avi48437.github.io/my-website/"
publishDir = "docs"
languageCode = "en-us"
title = "Avi | Personal Website"
theme = "PaperMod"

[params]
customCSS = ["css/custom.css"]

  [params.label]
    icon = "/images/profile.jpg"
    text = "Avinandan Roy"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Avi48437"

[[params.socialIcons]]
  name = "email"
  url = "mailto:avi48437@example.com"

[params.homeInfoParams]
  Title = "Welcome ðŸ‘‹"
  Content = "This is my personal website where I document my learning and projects."

[menu]

  [[menu.main]]
    name = "Bio"
    url = "/bio/"
    weight = 1

  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 3

  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 4

  [[menu.main]]
    name = "Travel"
    url = "/travel/"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6
